version: "3.4"
services:
  admin-tool-root:
    image: admin-tool-root:latest
    build:
      context: .
      dockerfile: ./AdminToolRootService/Dockerfile
    ports:
      - "5001:5001"
      - "5002:5002"
    restart: unless-stopped
